### ISSUE TITLE
刷新时报错：pointerIndex out of range pointerIndex=-1 pointerCount=1

### ISSUE THREAD

**Issue by GsBu** [nuptboyzhb/SuperSwipeRefreshLayout#62]
请问这个问题怎么解决？下面是Log：

java.lang.IllegalArgumentException: pointerIndex out of range pointerIndex=-1 pointerCount=1 at android.view.MotionEvent.nativeGetAxisValue(Native Method) at android.view.MotionEvent.getY(MotionEvent.java:2087) at android.support.v4.view.MotionEventCompat.getY(MotionEventCompat.java:521) at com.mddjob.android.view.ptr.SuperSwipeRefreshLayout.handlerPullTouchEvent(SuperSwipeRefreshLayout.java:920) at com.mddjob.android.view.ptr.SuperSwipeRefreshLayout.onTouchEvent(SuperSwipeRefreshLayout.java:819) at android.view.View.dispatchTouchEvent(View.java:9399) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2525) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2525) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2525) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2525) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2525) at android.view.ViewGroup.cancelAndClearTouchTargets(ViewGroup.java:2375) at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3051) at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3186) at

**Comment by KumariAnjuThakur** [comment]
Hi 
Is there any solution for this. I am still facing this crash

**Comment by KumariAnjuThakur** [comment]
Hi 
Any Update on this?
